# Generated by Django 5.0.3 on 2024-05-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_perpus_app', '0003_crips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='bobot',
            field=models.FloatField(),
        ),
    ]
