# Generated by Django 5.0.3 on 2024-05-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spk_perpus_app', '0008_rengking_rengking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rengking',
            name='rengking',
        ),
    ]
