# Generated by Django 5.0.3 on 2024-05-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_perpus_app', '0009_remove_rengking_rengking'),
    ]

    operations = [
        migrations.AddField(
            model_name='rengking',
            name='total_nilai',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
