# Generated by Django 5.0.3 on 2024-06-02 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_perpus_app', '0009_remove_rengking_rengking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaian',
            name='kriteria1',
        ),
        migrations.RemoveField(
            model_name='penilaian',
            name='kriteria4',
        ),
        migrations.RemoveField(
            model_name='penilaian',
            name='kriteria2',
        ),
        migrations.RemoveField(
            model_name='penilaian',
            name='kriteria3',
        ),
        migrations.AddField(
            model_name='penilaian',
            name='kriteria',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='kriteria', to='spk_perpus_app.kriteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaian',
            name='nilai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rengking',
            name='total_nilai',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Crips',
        ),
    ]
