# Generated by Django 5.0.3 on 2024-06-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_perpus_app', '0010_remove_penilaian_kriteria1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaian',
            name='nilai',
        ),
        migrations.AddField(
            model_name='penilaian',
            name='kriteria1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='penilaian',
            name='kriteria2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='penilaian',
            name='kriteria3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='penilaian',
            name='kriteria4',
            field=models.FloatField(default=0),
        ),
    ]
