# Generated by Django 5.0.3 on 2024-06-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spk_perpus_app', '0011_remove_penilaian_nilai_penilaian_kriteria1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaian',
            name='kriteria',
        ),
    ]
